### ISSUE TITLE
snip

### ISSUE THREAD

**Issue by MattTheTekie** [Austcool-Walker/N3RDP0RT4L-HQ#1]
~snip~

**Comment by MattTheTekie** [comment]
I've given you a chance, you can join the invite, but I can't name it back as you have the name.

**Comment by Austcool-Walker** [comment]
Sorry I'm not interested because you're morality is apparently broken and I don't want to work with a person who can't obey rules this is the official organization. I'm not working with a snitch unfortunately. You're lucky I haven't reported you to github for stealing....

**Comment by Austcool-Walker** [comment]
@MattTheTekie you can keep the older github organization if that makes you go away for good. you broke my trust many times. I'm really starting to question things atm.....

**Comment by MattTheTekie** [comment]
> @MattTheTekie you can keep the older github organization if that makes you go away for good. you broke my trust many times. I'm really starting to question things atm.....
I'm stressed with helping Flori with Linux, and redoing my MC server. I got pretty pissed for a while. I really shouldn't have started this "issue" in this repo to begin with. I typically would move on after a bit, but I really got overwhelmed with a lot so I just lashed out on you. You have every right to do this, and to be. I invited you back btw, not sure if you see the notification or not tbh.

**Comment by MattTheTekie** [comment]
> Sorry I'm not interested because you're morality is apparently broken and I don't want to work with a person who can't obey rules this is the official organization. I'm not working with a snitch unfortunately. You're lucky I haven't reported you to github for stealing....

Dead issue, but I'm the one who made pretty much everything from the website, to the readme's of our repo's. I could care less, but just wanted to put that out thier.
